### ISSUE TITLE
subscribe_session_ended() call results in TypeError: session_ended_handler() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by grishaburd** [snipsco/hermes-protocol#170]
In the documentation for subscribe_session_ended() it is stated that session-ended-callback function will be called with two arguments: hermes & sessionEndedMessage. However, I am getting an error message 

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/home/greg/environments/python3.6/lib/python3.6/site-packages/hermes_python/ffi/wrappers.py", line 61, in convert_arguments_when_invoking_function
    return func(hermes_client, *parsed_args)
TypeError: session_ended_handler() takes 2 positional arguments but 3 were given

By trial and error I noticed that the following implementation does not result in error. 
def session_ended_handler(hermes, undocumented_argument, sessionEndedMessage):
        print('\tEnding session id=%s ' %(sessionEndedMessage.session_id))

**Comment by grishaburd** [comment]
sorry, my mistake
