### ISSUE TITLE
[Python 3] AttributeError: 'bytes' object has no attribute 'encode' in TimeIntervalValue.from_c_repr

### ISSUE THREAD

**Issue by koenvervloesem** [snipsco/hermes-protocol#47]
In the class method `from_c_repr` of the class [ontology](https://github.com/snipsco/hermes-protocol/blob/develop/platforms/hermes-python/hermes_python/ontology.py).TimeIntervalValue `from_date` and `to_date` are _encoded_ to UTF-8. Shouldn't that be _decoded_, like in the rest of the classes?

I get the following error after converting one of my apps from Python 2 to 3:

```Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err] Traceback (most recent call last):
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]   File "_ctypes/callbacks.c", line 234, in 'calling callback function'
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]   File "/var/lib/snips/skills/snips-app-what-is-happening/venv/lib/python3.5/site-packages/hermes_python/hermes.py", line 63, in
 called_with_good_params                                                                              
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]     return func(self, *parsed_args)
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]   File "/var/lib/snips/skills/snips-app-what-is-happening/venv/lib/python3.5/site-packages/hermes_python/hermes.py", line 62, in
 <genexpr>                                                                                            
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]     parsed_args = (argtype.from_c_repr(arg.contents) for arg in (args))
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]   File "/var/lib/snips/skills/snips-app-what-is-happening/venv/lib/python3.5/site-packages/hermes_python/ontology.py", line 41,
in from_c_repr                                                                                                
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]     slots = SlotMap.from_c_repr(c_repr.slots.contents)
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]   File "/var/lib/snips/skills/snips-app-what-is-happening/venv/lib/python3.5/site-packages/hermes_python/ontology.py", line 72,
in from_c_repr                                                                                          
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]     nlu_slot = NluSlot.from_c_repr(c_slots_array_repr[i].contents)
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]   File "/var/lib/snips/skills/snips-app-what-is-happening/venv/lib/python3.5/site-packages/hermes_python/ontology.py", line 113,
 in from_c_repr                                                                                       
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]     slot = Slot.from_c_repr(c_repr.nlu_slot[0])
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]   File "/var/lib/snips/skills/snips-app-what-is-happening/venv/lib/python3.5/site-packages/hermes_python/ontology.py", line 148,
 in from_c_repr                                                                                               
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]     slot_value = SlotValue.from_c_repr(c_repr.value)
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]   File "/var/lib/snips/skills/snips-app-what-is-happening/venv/lib/python3.5/site-packages/hermes_python/ontology.py", line 186,
 in from_c_repr                                                                                       
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]     value = TimeIntervalValue.from_c_repr(c_repr_time_interval_value)      
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]   File "/var/lib/snips/skills/snips-app-what-is-happening/venv/lib/python3.5/site-packages/hermes_python/ontology.py", line 477,
 in from_c_repr                                                                                                           
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err]     from_date = c_repr.from_date.encode('utf-8') if c_repr.from_date else None
Jan 28 21:53:12 snips snips-skill-server[2635]: INFO:snips_skill_server_lib::runner: [what-is-happening][err] AttributeError: 'bytes' object has no attribute 'encode'
```
The text for this time interval value was "in winter". It also happens with other TimeIntervalValue objects, like "from January to February", "this weekend" and so on. I'm running this on Python 3.5.3.

If I change the encode to decode in ontology.py, the error disappears and my apps work again.

**Comment by anthonyray** [comment]
Good catch ! 
Thank you, it will be fixed in the next release : `0.1.29`.

**Comment by koenvervloesem** [comment]
Thanks for the fast response, Anthony!

**Comment by anthonyray** [comment]
Ongoing P.R ➡️ https://github.com/snipsco/hermes-protocol/pull/48
